/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询初始化状态
         * @description 免鉴权。GUI 启动据此决定走 setup 或正常态。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            initialized: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 建首个账户并签发该账户 root token
         * @description 免鉴权，仅 loopback，仅"未初始化"态可用（已有任何账户则返回 410）。
         *     建首个账户：接收用户名+密码 → KDF→KEK→随机 master_DEK[acct]→wrapped-DEK[acct] 落盘 + master_DEK[acct] 存 app 私有 keychain（作活跃）
         *     + 记 last_active_account_id → 签发该账户 root token（is_root=true + account_id，全 scope），明文 secret 仅返回一次。
         *     后续账户改走 POST /accounts（需任一已解锁账户的 root token）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 已初始化 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenCreated"];
                    };
                };
                410: components["responses"]["Gone"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改密码（重 wrap master_DEK[acct]，DEK 与历史内容不变）
         * @description 需 root token（tokens:manage 仅 root 持有）+ 当前密码（知识因子，双重确认）。作用于 caller 的 account_id 账户。
         *     校验当前密码（解开 wrapped-DEK[acct] 验证）→ 新密码 KDF 重 wrap master_DEK[acct] 落盘。master_DEK 与历史内容不变。
         *     不影响 token：token secret 独立随机、不派生自密码，改密后所有 token 仍有效；要撤销某 token 走 DELETE /tokens/{id}。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        current_password: string;
                        /** Format: password */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description 已修改 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出账户
         * @description 需 root token。返回所有账户摘要（含 is_active 标记活跃账户）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSummary"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * 追加账户（独立密码 + 独立 DEK，切换活跃）
         * @description 需任一已解锁账户的 root token（无全局 root，靠"已解锁即可建新账户"——已确认）。
         *     建独立账户：独立密码 → 独立 KEK → 独立 master_DEK[acct] → 独立 wrapped-DEK[acct] 落盘
         *     → 切换活跃至新账户（DEK 入 keychain + 记 last_active_account_id）
         *     → 签发该新账户 root token，明文 secret 仅返回一次。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountCreate"];
                };
            };
            responses: {
                /** @description 已创建并切为活跃 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenCreated"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除账户（删该账户全部数据）
         * @description 需 root token。删该账户的 DB + 文件树 + wrapped-DEK + keychain 项。
         *     活跃账户删除后回退到 setup/选账户态；活跃账户不可直接删（先切走），否则 409。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 切换/解锁账户
         * @description 免鉴权（密码作知识因子）+ 仅 loopback。输该账户密码 → KDF→KEK→解 wrapped-DEK[acct] 验证
         *     → master_DEK[acct] 入 keychain 作活跃（替换旧活跃项）→ 签发该账户 root token
         *     → 更新 last_active_account_id。旧活跃账户 DEK 移出 keychain（其 wrapped-DEK 留盘）。
         *     明文 root token secret 仅返回一次，并缓存 keychain 供日常免密。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 已解锁并切为活跃 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenCreated"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出会话 */
        get: {
            parameters: {
                query?: {
                    /** @description 分页游标 */
                    cursor?: string;
                    limit?: number;
                    source?: "realtime" | "imported";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        /**
         * 创建会话（提交音频做转译）
         * @description 仅本地 UI（sessions:write）。multipart 上传音频；服务经 ASR runtime 转译并加密落库。
         *     异步：返回 202 + transcribing 状态，轮询 GET /sessions/{id} 直到 status=completed。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        audio: string;
                        /**
                         * @description 可选；缺省 imported（文件导入语义；realtime 由 GUI 显式置位）
                         * @enum {string}
                         */
                        source?: "realtime" | "imported";
                        /**
                         * @description 可选；缺省 mixed（自动识别后置）
                         * @enum {string}
                         */
                        language?: "zh" | "en" | "mixed";
                        /** @description 可选；实时录制时由 GUI 壳填写的输入设备名称 */
                        input_device?: string;
                        /**
                         * Format: binary
                         * @description 可选；录音期剪贴板上下文的序列化 ClipboardContextFile（protobuf；application/octet-stream）。仅本地 GUI 壳提交，服务端立即加密落库为 context.pb.enc；缺失时与旧客户端完全兼容
                         */
                        clipboard_context?: string;
                    };
                };
            };
            responses: {
                /** @description 已接受，转译中 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            status: "transcribing";
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                413: components["responses"]["PayloadTooLarge"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索会话 */
        get: {
            parameters: {
                query: {
                    q: string;
                    cursor?: string;
                    limit?: number;
                    source?: "realtime" | "imported";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取会话详情（含转译文本、说话人） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        /** 删除会话及原始音频 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 获取原始音频（解密后返回） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 音频二进制 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/*": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重试失败会话（对已存音频重新转写）
         * @description 仅本地 UI（sessions:write）。对 status=failed 的会话重新转写已持久化的音频，免重传。
         *     status 回到 transcribing，轮询 GET /sessions/{id} 至 completed/failed。活跃 sidecar 占用或退避中返回 409。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已接受，转写中 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            status: "transcribing";
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/injection-plan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * 获取一次性注入计划（自动粘贴专用）
         * @description Tauri 原生层专用（root token，禁止经 WebView 通用 API 代理）。返回合成后的 plain/html 全文，
         *     原生层据此写剪贴板并模拟 Cmd+V；首次读取即标记消费，再次读取返回 410。
         *     响应附带 learning_ticket：自动粘贴成功且自动学习开启时，原生观察层凭它在有限观察窗口内
         *     提交一次学习；不启动观察时直接忽略，ticket 到期自然失效。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 注入计划（一次性，已标记消费） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InjectionPlan"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                410: components["responses"]["Gone"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出（明文目录树归档）
         * @description 作用于活跃账户：校验其密码（解开 wrapped-DEK[acct] 验证）后，按与存储同构的目录树（account/date/session/）
         *     导出明文：原始音频 + 转译文本（JSON，含说话人 + 时间戳）。返回 zip 归档。密码错误返回 403。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportRequest"];
                };
            };
            responses: {
                /** @description zip 归档 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出 token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Token"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 创建 token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenCreate"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenCreated"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 吊销 token */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已吊销 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reasoning/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出 cleanup provider 类型及 credential 要求
         * @description 仅 root token；返回 registry 的非敏感能力摘要。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderKind"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reasoning/provider-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出当前账户的 provider 配置
         * @description 仅 root token；不返回 credential。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderConfig"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        /**
         * 创建 provider 配置
         * @description 仅保存非 secret 配置；credential 使用专用 internal IPC 设置。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProviderConfigInput"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderConfig"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reasoning/provider-configs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 替换 provider 的非 secret 配置
         * @description endpoint/provider type 改变后既有 credential 进入 stale，且当前 cleanup 自动关闭。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProviderConfigInput"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderConfig"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        post?: never;
        /**
         * 删除 provider 配置
         * @description 先删除对应 Keychain credential，再删除配置；若当前选中则同步关闭 cleanup。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reasoning/provider-configs/{id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 单次验证 provider 可达性与已填写 model
         * @description 30 秒硬超时，不调用 /models、不重试；响应和错误均脱敏。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Probe 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderProbe"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/reasoning/provider-configs/{id}/credential": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 写入 provider credential 或显式选择无认证
         * @description Tauri 与 daemon 的内部 loopback 契约；仅 root token，禁止经 WebView 通用 API 代理，请求体不得记录日志。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialWriteRequest"];
                };
            };
            responses: {
                /** @description 已更新凭据状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CredentialStateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        post?: never;
        /**
         * 删除 provider credential
         * @description Tauri 与 daemon 的内部 loopback 契约；仅 root token，不存在对应的读取接口。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除并返回脱敏状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CredentialStateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                423: components["responses"]["Locked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dictionary/learning-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 消费 learning ticket 并提交一次学习
         * @description Tauri 原生观察层专用（root token，禁止经 WebView 通用 API 代理）。ticket 一次性、短期有效（TTL 2 分钟），
         *     内存绑定账户/Session/InjectionPlan generation；账户已切换、Session 非已完成或 generation 不匹配返回 409
         *     （learning_ticket_mismatch），过期、已消费或因容量淘汰返回 410（learning_ticket_expired /
         *     learning_ticket_consumed），编码非法返回 400（learning_ticket_invalid）。账户锁定沿用全局 423（locked）
         *     映射；ticket 在账户校验前已原子消费，任何拒绝均不可重放。
         *     mode=cleanup 时候选完全取自 ticket 绑定的已验证 Cleanup corrections（仅 proper_noun/phonetic），
         *     附带 candidates 或 mode 非法返回 400；mode=user_edit 的 candidates 最多 32 项，由 daemon 再次执行
         *     统一词条校验，词条数量或内容不合法返回 422（dictionary_invalid_term）。
         *     同一 Session 的 cleanup 采纳与 user_edit 学习归并为单次学习结果。错误 message 不含词条、ticket 或目标输入框文本。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LearningSubmission"];
                };
            };
            responses: {
                /** @description 学习写入结果；无实际新增时 learning_event_id=null */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                410: components["responses"]["Gone"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dictionary/learning-events/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningResult 返回的 learning_event_id */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撤销一批学习新增
         * @description Tauri 原生层专用（root token，禁止经 WebView 通用 API 代理）。仅删除该事件真正新增且仍为 learned 的词条
         *     （期间被用户编辑或确认提升为 manual 的不受影响）。幂等：重复撤销返回 undone_count=0。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description LearningResult 返回的 learning_event_id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 撤销结果（幂等） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UndoLearningResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanup/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取当前账户的 cleanup 设置
         * @description 仅 root token；无 settings 行时返回默认关闭。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CleanupSettings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        /**
         * 保存当前账户的 cleanup 设置
         * @description 仅在选中配置完整且 credential state 可用时允许启用；自定义 prompt 在保存时完整验证。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CleanupSettingsInput"];
                };
            };
            responses: {
                /** @description 已保存 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CleanupSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanup/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 执行一次 Prompt Studio cleanup 测试
         * @description 仅 root token；固定 30 秒硬超时，与 Probe 同账户 single-flight。草稿和结果只存在于本次请求，不创建 session/artifact/cache，也不修改正式 prompt。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CleanupTestRequest"];
                };
            };
            responses: {
                /** @description cleanup 测试成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CleanupTestResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 搜索/分页列出当前账户的 Dictionary 词条
         * @description 仅 root token。排序固定为 manual 在前、learned 在后，同来源按 updated_at DESC, id ASC。
         *     query 经统一规范化后对 normalized_term 做包含匹配（SQL LIKE 的 %、_ 与 escape 字符按普通字符处理）。
         *     cursor 绑定排序元组与 query 摘要：无法解码、与当前 query 不匹配或指向非法排序值时返回 400。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 可选；最多 128 个 Unicode scalar value */
                    query?: string;
                    /** @description 分页游标（上一页响应的 next_cursor 原样透传） */
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DictionaryPage"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 增量添加词条（单条或小批量）
         * @description 仅 root token。整请求校验：任一词条非法（空值/控制字符/纯标点空白/超长）或写入后将超过单账户容量
         *     （1,000 条）时返回 422 且零写入（dictionary_invalid_term / dictionary_limit_exceeded）。
         *     增量语义：请求内重复与既有 manual 词条计入 skipped_count；与既有 learned 词条冲突时更新其规范写法、
         *     提升为 manual 并清空 learning_event_id（计入 promoted）。新增、提升与去重在同一事务内完成，
         *     数据库 UNIQUE(normalized_term) 为最终并发去重边界；并发冲突折算到 skipped_count，不暴露 409。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddDictionaryEntriesRequest"];
                };
            };
            responses: {
                /** @description 增量写入统计（部分词条可能计入 promoted/skipped） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DictionaryMutationResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        /**
         * 清空当前账户全部用户词条
         * @description 仅 root token；幂等。删除全部 manual 与 learned 词条（未来系统保护词条不经本操作删除）。UI 必须先明确影响并二次确认。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已清空（幂等） */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 编辑词条的规范写法
         * @description 仅 root token。仅接受 {term}，由服务端执行权威规范化。与另一词条规范化冲突返回 409（dictionary_conflict）。
         *     编辑 learned 词条会将其提升为 manual 并清空 learning_event_id（不再受撤销影响）。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        term: string;
                    };
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DictionaryEntry"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        post?: never;
        /**
         * 删除单条词条
         * @description 仅 root token；幂等，存在或不存在均返回 204。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除（幂等） */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 预览 CSV 增量导入结果
         * @description 仅 root token。使用与正式导入相同的 CSV 解析、词条校验、规范化和当前词典状态，返回只读统计，
         *     不写入词条或学习事件。预览不锁定数据库状态；正式提交时必须重新校验并以提交结果为准。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportDictionaryCsvRequest"];
                };
            };
            responses: {
                /** @description 导入预览统计（解析/有效/预计新增/预计提升/预计跳过） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DictionaryImportPreview"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CSV 增量导入词条
         * @description 仅 root token。body 为 JSON 包裹的 UTF-8 CSV 文本：固定且仅允许单列 term 表头，RFC 4180 字段引用与双引号
         *     转义，允许 UTF-8 BOM 与 LF/CRLF，空白物理行忽略。CSV 语法错误、缺少/重复/未知表头、额外列、显式空 term、
         *     非法词条或超过 1,000 条数据记录时返回 422（dictionary_csv_invalid / dictionary_invalid_term），
         *     整次导入零写入。合法请求在一个事务内增量插入，不删除既有词条；合法重复记录按增量语义计入 skipped_count。
         *     客户端可先调用 /dictionary/imports/preview 展示预计统计；正式提交会重新校验，最终以本响应为准。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportDictionaryCsvRequest"];
                };
            };
            responses: {
                /** @description 导入统计（解析数/新增/提升/跳过） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DictionaryImportResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                422: components["responses"]["UnprocessableEntity"];
                423: components["responses"]["Locked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 导出当前账户全部用户词条为 CSV
         * @description Tauri 原生 command 专用（root token，禁止经 WebView 通用 API 代理）：原生层获取完整 CSV 后弹保存对话框
         *     写文件，文件路径不进入 daemon，导出不依赖 UI 当前分页状态。固定输出 term 表头 + RFC 4180 记录，
         *     不输出 BOM、内部 ID、来源、时间戳或事件 ID；顺序固定 normalized_term ASC, id ASC；
         *     导出内容可由 POST /dictionary/imports 无损重新导入。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description UTF-8 CSV（Content-Type: text/csv; charset=utf-8；下载文件名 seasnail-dictionary.csv） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                423: components["responses"]["Locked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出模型（已装 + 可装） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 开/关可选组件（punc/spk）
         * @description 仅本地 UI（sessions:write）。懒加载：仅持久化 `enabled`，下一条转写才挂载/卸载。
         *     未下载即开启 → 422。`{id}`∈{punc,spk} 为可选组件，与 activate（`{id}`∈后端 id）
         *     语义不同；同路径不同方法，不撞。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        enabled: boolean;
                    };
                };
            };
            responses: {
                /** @description 已持久化（懒，下条转写生效） */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        /**
         * 激活模型
         * @description 仅本地 UI（sessions:write）。`action=activate` 切换活跃模型（复用模型切换链路）；
         *     活跃 sidecar 转写中时返回 409。对已激活模型重复请求会返回当前状态，不重启运行时。
         *     最终 release 仅允许激活默认 GGUF 模型；非默认后端仅能由带
         *     `debug-backend-switching` 构建标识的内部迁移包显式选择，并在重启后生效。
         *     多模型下载、下载进度与卸载属于 P1，尚未暴露 API。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "activate";
                    };
                };
            };
            responses: {
                /** @description 已接受（下载中 / 切换中） */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按需下载组件（punc/spk）
         * @description 仅本地 UI（sessions:write）。对未下载组件触发后台下载（HTTP Range 断点续传 + 逐文件
         *     SHA-256 校验），立即返回 202；进度经 GET /models 的 Component.download_progress 轮询。
         *     已下载重复请求幂等返 202；下载进行中再发返 409。`{id}`∈{punc,spk}；spk 本次后置 → 422。
         *     与 `/models/{id}` 的 activate(POST)/开关(PUT) 路径段数不同，不撞。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已接受，下载中（轮询 GET /models 取 download_progress） */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example insufficient_scope */
                code: string;
                message: string;
            };
        };
        Speaker: {
            /** @example A */
            id: string;
            /** @example 说话人 A */
            label: string;
        };
        TranscriptUnit: {
            /** @description 关联 speakers[].id */
            speaker: string;
            /** @description 起始秒；UNTIMED 时为空 */
            start: number | null;
            /** @description 结束秒；UNTIMED 时为空 */
            end: number | null;
            text: string;
        };
        Transcript: {
            full_text: string;
            units: components["schemas"]["TranscriptUnit"][];
        };
        /** @enum {string} */
        SessionStatus: "transcribing" | "cleaning_up" | "completed" | "failed";
        /** @enum {string} */
        CleanupStatus: "not_requested" | "disabled" | "processing" | "succeeded" | "failed";
        /** @enum {string} */
        TextSource: "raw" | "cleanup";
        /** @enum {string} */
        ProviderType: "openai" | "openai_compatible_cloud" | "openai_compatible_self_hosted_public" | "openai_compatible_self_hosted_private";
        /** @enum {string} */
        CredentialState: "not_required" | "missing" | "bound" | "stale";
        /** @description 专用只写凭据载荷；no_auth 仅适用于允许无认证的自托管配置 */
        CredentialWriteRequest: {
            /** @constant */
            mode: "credential";
            /** Format: password */
            credential: string;
        } | {
            /** @constant */
            mode: "no_auth";
        };
        /** @description 凭据写入或删除后的脱敏状态；永不包含凭据 */
        CredentialStateResponse: {
            credential_state: components["schemas"]["CredentialState"];
        };
        ProviderKind: {
            provider_type: components["schemas"]["ProviderType"];
            requires_credential: boolean;
        };
        ProviderConfigInput: {
            name: string;
            provider_type: components["schemas"]["ProviderType"];
            /** @description 不允许 userinfo、query 或 fragment；响应返回规范化值 */
            endpoint: string;
            /** @description 用户手动填写；MVP 不调用 /models */
            model: string;
        };
        /** @description 非 secret 配置视图；永不包含 credential 或 API Key */
        ProviderConfig: {
            /** Format: uuid */
            id: string;
            name: string;
            provider_type: components["schemas"]["ProviderType"];
            /** @description 已规范化且不含 query 的 endpoint */
            endpoint: string;
            model: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            credential_state: components["schemas"]["CredentialState"];
        };
        CleanupSettingsInput: {
            enabled: boolean;
            /** Format: uuid */
            selected_provider_config_id: string | null;
            /** @description 仅语义部分；daemon 追加不可编辑协议尾缀 */
            custom_prompt: string | null;
        };
        CleanupSettings: components["schemas"]["CleanupSettingsInput"] & {
            /** @description 当前 daemon 版本内置的默认语义 prompt；仅供 root 设置界面只读展示 */
            default_prompt: string;
            /** @description daemon 强制追加且不可编辑的协议尾缀；仅供 root 设置界面只读展示 */
            protocol_prompt: string;
            /** Format: date-time */
            updated_at: string;
            selected_credential_state: components["schemas"]["CredentialState"] | null;
        };
        /** @description 脱敏 Probe 结果；不包含 endpoint、credential 或上游响应正文 */
        ProviderProbe: {
            model: string;
            elapsed_ms: number;
            /** @enum {string} */
            token_cap: "server_bounded" | "client_only";
            structured_output: boolean;
        };
        /** @description Prompt Studio 一次性测试输入；prompt_draft 不持久化，省略时使用正式设置中的 prompt */
        CleanupTestRequest: {
            /** Format: uuid */
            provider_config_id: string;
            text: string;
            prompt_draft?: string | null;
        };
        CleanupTestCorrection: {
            original_text: string;
            corrected_text: string;
            /** @enum {string} */
            kind: "phonetic" | "proper_noun" | "other_asr";
        };
        /** @description 已通过 JSON、正文、marker 和 correction 校验的结果；不含上游响应正文 */
        CleanupTestResult: {
            cleaned_text: string;
            corrections: components["schemas"]["CleanupTestCorrection"][];
            elapsed_ms: number;
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            source: "realtime" | "imported";
            /**
             * @description 自动识别
             * @enum {string}
             */
            language: "zh" | "en" | "mixed";
            duration_sec?: number;
            status: components["schemas"]["SessionStatus"];
            /** @description status=failed 时返回的失败原因 */
            failure_reason?: string | null;
            /** @description 使用的 ASR 模型标识 */
            model: string;
            /** @description 实时录制时的输入设备 */
            input_device?: string | null;
            /** @description 导入文件名 */
            file_name?: string | null;
            /** @description 创建时是否提交了剪贴板上下文；true 时 retry 复用已持久化的 context.pb.enc */
            context_present?: boolean;
            speakers?: components["schemas"]["Speaker"][];
            /** @description status=completed 时返回 */
            transcript?: components["schemas"]["Transcript"] | null;
        };
        /** @description 列表 / 搜索返回的会话摘要（不含 transcript） */
        SessionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            source: "realtime" | "imported";
            /** @enum {string} */
            language: "zh" | "en" | "mixed";
            duration_sec?: number;
            status: components["schemas"]["SessionStatus"];
            model?: string;
            /** @description 转译文本前若干字 */
            preview?: string;
            cleanup_status: components["schemas"]["CleanupStatus"];
            /** @description completed 时最终正文来源；transcribing/cleaning_up 时为 null */
            text_source?: components["schemas"]["TextSource"] | null;
            /** @description 仅 root UI 可见的稳定 cleanup 诊断码 */
            cleanup_error_code?: string | null;
        };
        SessionList: {
            items: components["schemas"]["SessionSummary"][];
            /** @description 不透明分页游标，透传回 cursor 查询参数 */
            next_cursor?: string | null;
        };
        Token: {
            /** Format: uuid */
            id: string;
            /** @description 所属账户（token 绑定此 account_id，仅可访问该账户且仅该账户已解锁时） */
            account_id: string;
            /** @description 用户命名 */
            name: string;
            /**
             * @description 仅展示前缀
             * @example ss_live_abcd…
             */
            prefix?: string;
            /** @description 是否 root token（每账户自己的 root，is_root + account_id；仅 setup/unlock 签发，持有 write/manage scope） */
            is_root?: boolean;
            scopes: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        TokenCreate: {
            name: string;
            /** @description 从可用 scope 中选；非 root 调用方不可授予 sessions:write / tokens:manage（daemon 硬约束），仅 root 自身持有 */
            scopes: string[];
        };
        TokenCreated: components["schemas"]["Token"] & {
            /** @description 完整 token 明文，仅创建时返回一次 */
            secret: string;
        };
        /** @description 新建账户（独立密码 + 独立 master DEK，与其它账户密钥完全隔离） */
        AccountCreate: {
            username: string;
            /** Format: password */
            password: string;
        };
        AccountSummary: {
            /** @description 不透明、稳定的账户标识（改名不影响密钥） */
            id: string;
            username: string;
            /** Format: date-time */
            created_at: string;
            /** @description 是否当前活跃账户（DEK 在 keychain） */
            is_active: boolean;
        };
        ExportRequest: {
            /**
             * Format: password
             * @description 用户密码（敏感操作再确认）
             */
            password: string;
            /** @description 空 = 导出全部会话 */
            session_ids?: string[];
        };
        Model: {
            /** @example whisper-base */
            id: string;
            /** @enum {string} */
            runtime: "whisper" | "funasr" | "gguf" | "sherpa_onnx";
            size_bytes?: number;
            languages?: string[];
            /** @enum {string} */
            diarization?: "builtin" | "external" | "none";
            /**
             * @description 当前安装/激活状态
             * @enum {string}
             */
            status: "not_installed" | "installed" | "active";
            /** @description 是否随 app 内置 */
            bundled?: boolean;
            /** @description 是否默认模型 */
            default?: boolean;
            /** @description funasr 后端可选组件（punc/spk）状态；无组件的运行时省略。 */
            components?: components["schemas"]["Component"][];
        };
        Component: {
            /**
             * @description 组件 id（punc/spk）
             * @example punc
             */
            id: string;
            /** @description 是否随 app 内置 */
            bundled: boolean;
            /** @description 已下载（用户目录或内置有该组件 → 可懒挂载） */
            downloaded: boolean;
            /** @description 开关（daemon settings，懒加载：下条转写才挂/卸） */
            enabled: boolean;
            /** @description UI 是否可操作（spk 后置→false；punc→true） */
            toggleable: boolean;
            /** @description 组件体积（M4.1 随包 models-manifest.json 提供权威值） */
            size_bytes: number;
            /**
             * Format: float
             * @description 下载进度 0.0–1.0（M4 下载期）
             */
            download_progress: number | null;
        };
        /** @description 账户级 Dictionary 词条视图；不暴露 normalized_term、learning_event_id 或历史输入全文 */
        DictionaryEntry: {
            /** Format: uuid */
            id: string;
            /** @description 用户确认的规范写法（保留大小写与兼容字符形式） */
            term: string;
            /**
             * @description manual=用户明确维护；learned=自动学习获得
             * @enum {string}
             */
            source: "manual" | "learned";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DictionaryPage: {
            items: components["schemas"]["DictionaryEntry"][];
            /** @description 不透明分页游标，透传回 cursor 查询参数；与当前 query 摘要绑定，末页为 null */
            next_cursor?: string | null;
        };
        /** @description 单条或小批量增量添加；整请求校验，任一词条非法或写入后超账户容量则零写入 */
        AddDictionaryEntriesRequest: {
            terms: string[];
        };
        /** @description 增量写入统计；请求内重复及与既有 manual 冲突计入 skipped_count，与既有 learned 冲突提升为 manual */
        DictionaryMutationResult: {
            added: components["schemas"]["DictionaryEntry"][];
            /** @description 由 learned 提升为 manual 的词条（learning_event_id 已清空，不再受撤销影响） */
            promoted: components["schemas"]["DictionaryEntry"][];
            skipped_count: number;
        };
        /** @description JSON 包裹的 UTF-8 CSV 文本；固定单列 term 表头，RFC 4180 字段引用与双引号转义，允许 UTF-8 BOM 与 LF/CRLF；解析或校验失败整次零写入 */
        ImportDictionaryCsvRequest: {
            /** @description CSV 全文（按 UTF-8 计最多 1 MiB）；解析后数据记录最多 1000 条 */
            csv: string;
        };
        DictionaryImportResult: components["schemas"]["DictionaryMutationResult"] & {
            /** @description CSV 解析出的数据记录数（不含表头与空白物理行） */
            parsed_count: number;
        };
        /**
         * @description CSV 只读预览统计。valid_count 为通过词条校验并按 normalized_term 去重后的数量；
         *     added_count、promoted_count、skipped_count 基于预览时的当前词典计算，正式提交仍会在事务内重新校验。
         */
        DictionaryImportPreview: {
            /** @description CSV 解析出的数据记录数（不含表头与空白物理行） */
            parsed_count: number;
            /** @description 校验通过且按 normalized_term 去重后的词条数 */
            valid_count: number;
            /** @description 按预览时状态预计新增的词条数 */
            added_count: number;
            /** @description 按预览时状态预计由 learned 提升为 manual 的词条数 */
            promoted_count: number;
            /** @description 请求内重复及与既有 manual 冲突而预计跳过的记录数 */
            skipped_count: number;
        };
        /** @description 一次性注入计划；首次读取即消费，再读返回 410。learning_ticket 为自动学习能力票据，原生层在自动学习关闭或不启动观察时直接忽略（到期自然失效） */
        InjectionPlan: {
            /** @description 合成后的普通全文（含剪贴板上下文标记） */
            plain: string;
            /** @description 同位置的安全 HTML（ASR 文本与系统标记已转义、富文本已经过滤）；为空串时原生层降级为纯文本注入 */
            html: string;
            /** @description 一次性短期学习票据（base64url；内存绑定账户/Session/本 plan generation，TTL 2 分钟，daemon 重启失效） */
            learning_ticket: string;
        };
        /**
         * @description 消费 learning ticket 提交一次学习。mode=cleanup：候选完全取自 ticket 绑定的已验证 Cleanup corrections，candidates 必须省略或为空；
         *     mode=user_edit：candidates 为原生层从用户修改中提取的候选词条，daemon 侧再次执行统一词条校验。
         */
        LearningSubmission: {
            /** @description InjectionPlan 返回的 learning_ticket */
            ticket: string;
            /** @enum {string} */
            mode: "cleanup" | "user_edit";
            /** @description 仅 mode=user_edit 时携带；mode=cleanup 时必须省略或为空 */
            candidates?: string[];
        };
        /** @description 学习写入结果；没有实际新增时 learning_event_id=null，调用方不显示成功通知 */
        LearningResult: {
            /** @description 本批学习事件 ID（撤销凭据）；仅在实际新增时返回 */
            learning_event_id: string | null;
            /** @description 本批真正新增的规范词条（此前已存在的不重复计入） */
            added_terms: string[];
        };
        UndoLearningResult: {
            /** @description 实际删除的词条数；重复撤销返回 0（幂等） */
            undone_count: number;
        };
    };
    responses: {
        /** @description 请求字段或语义无效 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未携带或无效 token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 权限不足（缺 scope / 密码错误） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 当前资源状态与请求冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 一次性资源已消费、过期或不可再用 */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求体超过接口限制 */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求可解析，但内容或当前配置不满足接口契约 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 目标账户未解锁（DEK 不在内存，需先 POST /accounts/{id}/unlock） */
        Locked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 所需本地服务、bundle 或 manifest 暂不可用 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
