#!/usr/bin/env python3
"""Reproduce procedural/CC-BY fixtures from hash-verified local FLEURS WAV inputs."""
from pathlib import Path
import argparse
import hashlib
import io
import json
import struct
import subprocess
import tempfile
import wave

ROOT = Path(__file__).resolve().parents[1]


def pipeline_wav():
    """One second of integer triangle-wave PCM, with no speech or external input."""
    frames = b''.join(struct.pack('<h', ((i % 64) if i % 64 < 32 else 63 - i % 64) * 128 - 1984)
                      for i in range(16000))
    return wav_bytes(frames)


def wav_bytes(frames):
    result = io.BytesIO()
    with wave.open(result, 'wb') as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(16000)
        wav.writeframes(frames)
    return result.getvalue()


def verified_sources(directory, provenance):
    # Validate all sources before producing outputs; never bless arbitrary WAVs.
    result = []
    for sample in provenance['samples']:
        source = directory / sample['input_file']
        if source.is_symlink() or not source.is_file():
            raise ValueError('Missing regular FLEURS source WAV: ' + sample['input_file'])
        content = source.read_bytes()
        if len(content) != sample['source_audio_size_bytes'] or hashlib.sha256(content).hexdigest() != sample['source_audio_sha256']:
            raise ValueError('FLEURS source WAV checksum mismatch: ' + sample['input_file'])
        result.append((sample, source))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-dir', required=True, type=Path,
                        help='Directory of the two original WAVs named in assets/audio-provenance.json')
    parser.add_argument('--ffmpeg', default='ffmpeg', help='FFmpeg executable; used only during regeneration')
    parser.add_argument('--check', action='store_true', help='Compare regenerated bytes without modifying fixtures')
    args = parser.parse_args()
    provenance = json.loads((ROOT / 'assets/audio-provenance.json').read_text())
    sources = verified_sources(args.source_dir, provenance)
    rendered = {'audio/pipeline-v1.wav': pipeline_wav()}
    with tempfile.TemporaryDirectory(prefix='seasnail-licensed-audio-') as folder:
        for sample, source in sources:
            target = Path(folder) / (sample['id'] + '.wav')
            subprocess.run([args.ffmpeg, '-v', 'error', '-nostdin', '-i', str(source),
                            '-map_metadata', '-1', '-ac', '1', '-ar', '16000',
                            '-c:a', 'pcm_s16le', '-fflags', '+bitexact', '-flags:a', '+bitexact', str(target)],
                           check=True, timeout=30)
            with wave.open(str(target), 'rb') as wav:
                if (wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) != (1, 2, 16000):
                    raise ValueError('Unexpected normalized WAV format')
                frames = wav.readframes(wav.getnframes())
                if not frames:
                    raise ValueError('Empty source audio')
            rendered[sample['output_path'].removeprefix('assets/')] = wav_bytes(frames)
    # The checked-in manifest pins outputs. Regeneration never changes references,
    # thresholds, hashes or approval metadata to make new bytes pass silently.
    manifest = json.loads((ROOT / 'assets/manifest.json').read_text())
    expected = {sample['audio_path'].removeprefix('assets/'): sample['audio_sha256'] for sample in manifest['samples']}
    pipeline = json.loads((ROOT / 'assets/pipeline-audio.json').read_text())
    expected[pipeline['audio_path'].removeprefix('assets/')] = pipeline['audio_sha256']
    for name, content in rendered.items():
        if hashlib.sha256(content).hexdigest() != expected[name]:
            raise ValueError('Regenerated audio differs from pinned output; review/rebaseline required: ' + name)
    for name, content in rendered.items():
        target = ROOT / 'assets' / name
        if args.check:
            if target.read_bytes() != content:
                raise ValueError('Checked-in audio differs from verified regeneration: ' + name)
        else:
            target.write_bytes(content)
    print('3 fixtures verified' if args.check else '3 pinned fixtures reproduced; no system voices used')


if __name__ == '__main__':
    main()
